project:
  type: website
  output-dir: docs


listing:
  contents: posts
  sort: "date desc"  # 日期最新的在前面

format:
  html:
    theme:
      light: flatly
      dark: darkly
    # css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    toc-title: "目錄"
    number-sections: false
    # self-contained: true
    # code-fold: true
    # code-copy: true
    # code-tools: true
    # code-tools-position: top
    # include-before-body: toc.html

website:
  title: "紙魚ㄉ部落格"
  page-navigation: true
  navbar:
    right:
      - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com









